# Pre-commit hooks configuration
# Minimal setup focusing on code formatting and basic checks
repos:
  # Ruff - Python formatting (always works)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff-format
        name: Format Python code with ruff

  # Basic file maintenance
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']

  # Optional: Ruff linting (may show warnings but won't block commits)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        name: Lint Python code with ruff (warnings only)
        args: [--fix, --exit-zero]  # --exit-zero means don't fail on warnings
